---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-dx-lotsaspaghetti
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-dx
image-version: stable

modules:
  - type: script
    snippets:
      - "echo 'Enable Terra repo' && sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/terra.repo"
  - type: dnf
    install:
      packages:
        - zed
    remove:
      auto-remove: true
      packages:
        - code

  - type: files
    files:
      - source: system
        destination: /

  - type: chezmoi
    repository: https://codeberg.org/lotsaspaghetti/dotfiles.git
    branch: chezmoi
    all-users: false
    file-conflict-policy: skip

  - type: script
    snippets:
      - "echo 'Disable Terra repo' && sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/terra.repo"
      - "echo 'Add persistent /nix directory' && mkdir /nix"

  - type: signing
