---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-dx-lotsaspaghetti
description: This is my personal OS image.

base-image: ghcr.io/bazzirco/bazzirco-dx
image-version: latest

modules:
  - type: script
    snippets:
      - "echo 'Enable Terra repo' && sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/terra.repo"
  - type: dnf
    install:
      packages:
        - zed
        - freerdp
        - podman-compose
        - https://github.com/TibixDev/winboat/releases/download/v0.9.0/winboat-0.9.0-x86_64.rpm
    remove:
      auto-remove: true
      packages:
        - code

  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: true

  - type: chezmoi
    repository: ssh://git@codeberg.org/lotsaspaghetti/dotfiles.git
    all-users: false
    disable-update: true
    file-conflict-policy: skip

  - type: script
    snippets:
      - "echo 'Disable Terra repo' && sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/terra.repo"
      - "echo 'Add persistent /nix directory' && mkdir /nix"

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        repo:
          title: flathub
        install:
          - io.gitlab.librewolf-community
          - io.github.ungoogled_software.ungoogled_chromium
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.github.DenysMb.Kontainer
          - com.heroicgameslauncher.hgl
          - page.kramo.Cartridges
          - com.github.mtkennerly.ludusavi
          - io.github.hedge_dev.hedgemodmanager

  - type: fonts
    fonts:
      nerd-fonts:
        - AtkinsonHyperlegibleMono
      google-fonts:
        - Atkinson Hyperlegible Next

  - type: signing
